# Generated by Django 4.2.6 on 2023-10-30 19:15

import autoslug.fields
from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('event_date', models.DateTimeField()),
                ('location', models.CharField(max_length=50)),
                ('host', models.CharField(default='KUASA', max_length=50)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=events.models.event_image_file_path)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='title', unique=True)),
            ],
        ),
    ]
