# Generated by Django 4.2.5 on 2023-09-16 16:21

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.profile_image_file_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
