# Generated by Django 4.2.5 on 2023-09-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_phone_number_alter_user_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_corporate_member',
            field=models.BooleanField(default=False, verbose_name='Is Corporate Member'),
        ),
    ]
